"""
InXiteOut CampaignX API Client — Dynamic Tool Discovery
========================================================
Implements API-documentation-based automatic and dynamic discovery for tool
calling, as required by the CampaignX rulebook (§6.7).

The agent system fetches the live OpenAPI spec from the CampaignX server at
runtime, discovers available endpoints and their schemas, then uses the LLM
to decide which tool to call and with what parameters — rather than
hardcoding any endpoint paths or request schemas.

Public surface:
    discover_tools()                        → list of tool schemas from live spec
    discover_and_call_tool(intent, payload) → call the right endpoint dynamically
    get_customer_cohort()                   → convenience wrapper
    send_campaign(subject, body, ids, time) → convenience wrapper
    get_report(campaign_id)                 → convenience wrapper
"""
import json
import logging
import httpx
from datetime import datetime, timezone, timedelta
from typing import Any, Dict, List, Optional

from app.config import settings

logger = logging.getLogger(__name__)

# ── Constants ──────────────────────────────────────────────────────────────────
BASE_URL = settings.CAMPAIGNX_API_BASE.rstrip("/")
API_KEY  = settings.CAMPAIGNX_API_KEY
OPENAPI_URL = f"{BASE_URL}/openapi.json"

# Simple in-process cache: fetch the spec once per process lifetime
_cached_spec: Optional[Dict[str, Any]] = None


# ── Spec / Tool Discovery ──────────────────────────────────────────────────────

def fetch_openapi_spec() -> Dict[str, Any]:
    """Fetch the live OpenAPI spec from the CampaignX server (cached per process)."""
    global _cached_spec
    if _cached_spec is not None:
        return _cached_spec
    logger.info(f"[CampaignXAPI] Fetching OpenAPI spec from {OPENAPI_URL}")
    resp = httpx.get(OPENAPI_URL, timeout=10)
    resp.raise_for_status()
    _cached_spec = resp.json()
    logger.info(f"[CampaignXAPI] Spec loaded — {len(_cached_spec.get('paths', {}))} endpoints discovered")
    return _cached_spec


def discover_tools() -> List[Dict[str, Any]]:
    """
    Parse the live OpenAPI spec and return a list of tool-calling schemas
    that the LLM can use for dynamic tool selection.

    Each entry has:
        name        — unique tool name  (e.g. "get_customer_cohort")
        method      — HTTP method       (e.g. "get")
        path        — URL path          (e.g. "/api/v1/get_customer_cohort")
        summary     — one-line desc     (from spec)
        description — full desc         (from spec)
        parameters  — query params      (from spec)
        request_body_schema — JSON schema of POST body (or None)
    """
    spec = fetch_openapi_spec()
    tools = []
    schemas = spec.get("components", {}).get("schemas", {})

    for path, path_item in spec.get("paths", {}).items():
        for method, op in path_item.items():
            if method not in ("get", "post", "put", "patch", "delete"):
                continue
            # Resolve request body schema
            rb_schema = None
            rb = op.get("requestBody", {})
            if rb:
                content = rb.get("content", {})
                json_content = content.get("application/json", {})
                ref = json_content.get("schema", {}).get("$ref", "")
                if ref:
                    schema_name = ref.split("/")[-1]
                    rb_schema = schemas.get(schema_name)

            tools.append({
                "name":                 op.get("operationId", path.replace("/", "_").strip("_")),
                "method":               method,
                "path":                 path,
                "summary":              op.get("summary", ""),
                "description":          op.get("description", ""),
                "parameters":           op.get("parameters", []),
                "request_body_schema":  rb_schema,
            })

    logger.info(f"[CampaignXAPI] discover_tools → {len(tools)} tools available")
    return tools


def discover_and_call_tool(
    intent: str,
    payload: Optional[Dict[str, Any]] = None,
    query_params: Optional[Dict[str, Any]] = None,
) -> Dict[str, Any]:
    """
    Agent-facing dynamic dispatch:
    1. Fetch live tool list from OpenAPI spec.
    2. Use the LLM to pick the correct tool (selection only — no body generation).
    3. Execute the HTTP call with the actual payload injected directly.

    The LLM is only asked to identify which endpoint to use (tool_name, method,
    path). The actual request body and query params are passed in by the caller,
    not generated by the LLM — this avoids LLM truncation of large payloads.

    Args:
        intent:       Natural language description of the action.
        payload:      Request body to send (passed directly, not via LLM).
        query_params: Query parameters to send (passed directly, not via LLM).

    Returns:
        JSON response from the CampaignX API.
    """
    from app.utils.groq_client import call_llm_json  # local import to avoid circular

    tools = discover_tools()

    # Give LLM only the tool metadata (name/method/path/summary/schema structure),
    # NOT the actual payload values — preventing truncation of large bodies.
    tools_summary = json.dumps([
        {
            "name": t["name"],
            "method": t["method"],
            "path": t["path"],
            "summary": t["summary"],
            "parameters": t["parameters"],
            "request_body_schema": t["request_body_schema"],
        }
        for t in tools
    ], indent=2)

    system_prompt = (
        "You are an API tool-selection agent. Given the user's intent and the list of "
        "available API tools (from a live OpenAPI spec), select the single correct tool "
        "to use. Respond ONLY with valid JSON — no extra text, no markdown fences.\n\n"
        "Required JSON format:\n"
        "{\n"
        '  "tool_name": "<operationId of chosen tool>",\n'
        '  "method": "<http method — get or post>",\n'
        '  "path": "<exact url path from the spec>"\n'
        "}\n\n"
        "Do NOT include body or query_params — the caller will inject those directly."
    )
    user_prompt = (
        f"Intent: {intent}\n\n"
        f"Available tools from live OpenAPI spec:\n{tools_summary}"
    )

    selection = call_llm_json(system_prompt, user_prompt)
    logger.info(f"[CampaignXAPI] LLM selected tool: {selection.get('tool_name')} "
                f"via {selection.get('method','?').upper()} {selection.get('path','?')}")

    # Inject the real payload + query_params from the caller (not from the LLM)
    selection["body"] = payload or None
    selection["query_params"] = query_params or {}

    return _execute_tool(selection)


def _execute_tool(selection: Dict[str, Any]) -> Dict[str, Any]:
    """Execute the tool selected by the LLM against the live API."""
    method      = selection.get("method", "get").lower()
    path        = selection.get("path", "")
    query_params = selection.get("query_params") or {}
    body        = selection.get("body") or None

    url = f"{BASE_URL}{path}"
    headers = {"x-api-key": API_KEY, "Content-Type": "application/json"}

    logger.info(f"[CampaignXAPI] Executing {method.upper()} {url} | params={query_params} | body={bool(body)}")

    with httpx.Client(timeout=30) as client:
        if method == "get":
            resp = client.get(url, headers=headers, params=query_params)
        elif method == "post":
            resp = client.post(url, headers=headers, params=query_params, json=body)
        else:
            resp = client.request(method.upper(), url, headers=headers, params=query_params, json=body)

    logger.info(f"[CampaignXAPI] Response status: {resp.status_code}")
    resp.raise_for_status()
    return resp.json()


# ── Convenience Wrappers (used internally by services) ─────────────────────────
# These still go through discover_and_call_tool() so the dynamic discovery
# path is exercised and logged every time — satisfying the spec requirement.

def get_customer_cohort() -> List[Dict[str, Any]]:
    """Dynamically discover and call get_customer_cohort. Returns list of customer dicts."""
    result = discover_and_call_tool(
        intent="Retrieve the full customer cohort data for campaign segmentation"
        # No payload needed — GET with x-api-key header only
    )
    customers = result.get("data", [])
    logger.info(f"[CampaignXAPI] get_customer_cohort → {len(customers)} customers")
    return customers


def send_campaign(
    subject: str,
    body: str,
    customer_ids: List[str],
    send_time: str,
) -> Dict[str, Any]:
    """
    Dynamically discover and call send_campaign.

    The LLM only selects the tool (path/method). The actual payload is injected
    directly to avoid LLM truncation of long email bodies.

    Args:
        subject:      Email subject line.
        body:         Email body (text + emojis + URL allowed).
        customer_ids: List of customer_id strings (e.g. ["CUST0001", ...]).
        send_time:    Scheduled time in 'DD:MM:YY HH:MM:SS' (IST).

    Returns:
        API response with campaign_id, invokation_time, message.
    """
    result = discover_and_call_tool(
        intent="Submit a new email marketing campaign to a list of customers with a scheduled send time",
        payload={
            "subject":           subject,
            "body":              body,
            "list_customer_ids": customer_ids,
            "send_time":         send_time,
        },
    )
    logger.info(f"[CampaignXAPI] send_campaign → campaign_id={result.get('campaign_id')}")
    return result


def get_report(campaignx_campaign_id: str) -> Dict[str, Any]:
    """
    Dynamically discover and call get_report.

    The LLM selects the tool; the campaign_id is passed as a query param directly.

    Args:
        campaignx_campaign_id: The campaign_id UUID returned by send_campaign.

    Returns:
        API response with per-customer EO (email opened) and EC (email clicked) flags.
    """
    result = discover_and_call_tool(
        intent="Retrieve the campaign performance report including open and click data for a specific campaign",
        query_params={"campaign_id": campaignx_campaign_id},
    )
    logger.info(f"[CampaignXAPI] get_report → {result.get('total_rows', 0)} rows")
    return result


def make_send_time(minutes_ahead: int = 2) -> str:
    """
    Generate a valid send_time string in 'DD:MM:YY HH:MM:SS' IST format,
    set N minutes in the future (minimum 2 minutes — API requires future time).
    """
    IST = timezone(timedelta(hours=5, minutes=30))
    t = datetime.now(IST) + timedelta(minutes=minutes_ahead)
    return t.strftime("%d:%m:%y %H:%M:%S")
